### ISSUE TITLE
Testing during development

### ISSUE THREAD

**Issue by thiendangvan** [Portkey-Wallet/react-native-sdk#117]
hi @wade-portkey, i've forked the sdk and i'm customizing the SDK but i don't know how to see the latest update when i change the code. could you help to share how to run the SDK during development? thanks

**Comment by wade-portkey** [comment]
> hi @wade-portkey, i've forked the sdk and i'm customizing the SDK but i don't know how to see the latest update when i change the code. could you help to share how to run the SDK during development? thanks

hi @thiendangvan ,  We are currently writing a guide document for you, expected to be completed this afternoon. Please wait for this.

**Comment by thiendangvan** [comment]
> @thiendangvan , We are currently writing a guide document for you, expected to be completed this afternoon. Please wait for this.

thanks @wade-portkey, take your time

**Comment by wade-portkey** [comment]
hi, @thiendangvan 
We wrote a doc(https://github.com/Portkey-Wallet/react-native-sdk/blob/master/RUN-PROJECT.md) that you can refer to. 
I initially wanted to run an Expo project, but after integrating the SDK, the hot reload feature stopped working well. So, you won't see the UI effects immediately after updating the code. Consequently, I had to use a native project to run this project. Due to time constraints, we only documented the running process for iOS. You can refer to it first. If running the Android project is needed later, we will supplement it.

**Comment by thiendangvan** [comment]
> hi, @thiendangvan We wrote a doc(https://github.com/Portkey-Wallet/react-native-sdk/blob/master/RUN-PROJECT.md) that you can refer to. I initially wanted to run an Expo project, but after integrating the SDK, the hot reload feature stopped working well. So, you won't see the UI effects immediately after updating the code. Consequently, I had to use a native project to run this project. Due to time constraints, we only documented the running process for iOS. You can refer to it first. If running the Android project is needed later, we will supplement it.

Thanks @wade-portkey, I'm working on IOS first so it's okay

**Comment by thiendangvan** [comment]
sorry @wade-portkey, i've followed your instructions, but i cannot run the project in xcode.

<img width="937" alt="image" src="https://github.com/Portkey-Wallet/react-native-sdk/assets/154788705/7847238e-250c-4a03-98c6-9a92f81a0fc6">


currently, i'm doing the below steps to test my code:
1. change the code to match our UI design
2. yarn build
3. npm pack
4. unpack portkey-react-native-sdk-2.0.1.tgz and get the package folder
5. switch to my test project and run "yarn add path/to/package" (path to folder just unpacked)
6. yarn ios

but it takes too much time for testing :((, hope we can find a solution for testing during the development like the hot reload

**Comment by thiendangvan** [comment]
> sorry @wade-portkey, i've followed your instructions, but i cannot run the project in xcode.
> 
> <img alt="image" width="937" src="https://private-user-images.githubusercontent.com/154788705/322807207-7847238e-250c-4a03-98c6-9a92f81a0fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjQxMTcsIm5iZiI6MTcxMzI2MzgxNywicGF0aCI6Ii8xNTQ3ODg3MDUvMzIyODA3MjA3LTc4NDcyMzhlLTI1MGMtNGEwMy05OGM2LTlhOTJmODFhMGZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMDM2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTI5MWY0NzMzNjZiOGJmMTdlODgwN2MxZjQ0M2ZkYzI2Njk4ZDZkZDE4YjdmYjMwMWZmZmFmYjlhYWZkMTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1ewIr201jOELqWEURi52Hii7MwtCLabEPlivHdmt6ZU">
> currently, i doing the below steps to test my code:
> 
> 1. change code to match our UI design
> 2. yarn build
> 3. npm pack
> 4. unpack portkey-react-native-sdk-2.0.1.tgz and get the package folder
> 5. switch to my test project and run "yarn add path/to/package" (path to folder just unpacked)
> 6. yarn ios
> 
> but it takes too much time for testing :((, hope we can find a solution for testing during the development like the hot reload

**Comment by wade-portkey** [comment]
hi, @thiendangvan ,
I think you can directly modify the code in the react-native-sdk project to implement your UI, then run the iOS project under `react-native-sdk/app_ios` to test your UI modifications. 
Once all UI changes are completed, you can publish react-native-sdk with a different name (e.g., portkey-fod) to npm (before publishing, execute `yarn build` in the root directory), and then add the package to your project using `yarn add portkey-fod`. Alternatively, you can also add it to the project by using `yarn add file:/path/to/local/folder` without publishing it to npm.
Please communicate with us if you have any questions.

**Comment by thiendangvan** [comment]
> hi, @thiendangvan , I think you can directly modify the code in the react-native-sdk project to implement your UI, then run the iOS project under `react-native-sdk/app_ios` to test your UI modifications. Once all UI changes are completed, you can publish react-native-sdk with a different name (e.g., portkey-fod) to npm (before publishing, execute `yarn build` in the root directory), and then add the package to your project using `yarn add portkey-fod`. Alternatively, you can also add it to the project by using `yarn add file:/path/to/local/folder` without publishing it to npm. Please communicate with us if you have any questions.

yeah i got it @wade-portkey, i can run the app_ios now, i have to change 16.20.2 to 16.20.2_1 to make it work. if not i got this error:
```
Node found at: /opt/homebrew/Cellar/node@16/16.20.2/bin/node
/Users/thiendang201/Documents/NCCWorkSpace/test/react-native-sdk-test/app_ios/Pods/../../node_modules/react-native/ReactCommon/../scripts/react_native_pods_utils/script_phases.sh: line 34: /opt/homebrew/Cellar/node@16/16.20.2/bin/node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
<img width="664" alt="Screenshot 2024-04-16 at 22 39 20" src="https://github.com/Portkey-Wallet/react-native-sdk/assets/154788705/d2ee64bb-a700-49d1-8112-e76b815d38ce">

**Comment by wade-portkey** [comment]
> > hi, @thiendangvan , I think you can directly modify the code in the react-native-sdk project to implement your UI, then run the iOS project under `react-native-sdk/app_ios` to test your UI modifications. Once all UI changes are completed, you can publish react-native-sdk with a different name (e.g., portkey-fod) to npm (before publishing, execute `yarn build` in the root directory), and then add the package to your project using `yarn add portkey-fod`. Alternatively, you can also add it to the project by using `yarn add file:/path/to/local/folder` without publishing it to npm. Please communicate with us if you have any questions.
> 
> yeah i got it @wade-portkey, i can run the app_ios now, i have to change 16.20.2 to 16.20.2_1 to make it work. if not i got this error:
> 
> ```
> Node found at: /opt/homebrew/Cellar/node@16/16.20.2/bin/node
> /Users/thiendang201/Documents/NCCWorkSpace/test/react-native-sdk-test/app_ios/Pods/../../node_modules/react-native/ReactCommon/../scripts/react_native_pods_utils/script_phases.sh: line 34: /opt/homebrew/Cellar/node@16/16.20.2/bin/node: No such file or directory
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> <img alt="Screenshot 2024-04-16 at 22 39 20" width="664" src="https://private-user-images.githubusercontent.com/154788705/322909975-d2ee64bb-a700-49d1-8112-e76b815d38ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODI0ODYsIm5iZiI6MTcxMzI4MjE4NiwicGF0aCI6Ii8xNTQ3ODg3MDUvMzIyOTA5OTc1LWQyZWU2NGJiLWE3MDAtNDlkMS04MTEyLWU3NmI4MTVkMzhjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxNTQzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDJmYWNkMGYxM2JmZDgzM2EyNmExYTVmZDRkYmQ3M2NkM2VlNzFlNGJmMjc3YjM0Zjg3ZjllOWFjYTRkNjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4JD73-zL18TKdaiugAJ8jTPYDao2eibrJJ7s9GAVw10">

hi, @thiendangvan :
very glad to see you have solved this problem. sorry, I didn't realize that the Node.js version would cause you trouble. my local Node.js version is v18.19.0 for your reference.
