### ISSUE TITLE
FAILURE: Build failed with an exception. Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.

### ISSUE THREAD

**Issue by thiendangvan** [Portkey-Wallet/react-native-sdk#35]
### I got the below error when tried to run the project:
```
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':invertase_react-native-apple-authentication', ':portkey_react-native-sdk', ':expo-modules-core', ':react-native-gesture-handler', ...

> Task :react-native-gesture-handler:assertNoMultipleInstances FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\react-native-gesture-handler\android\build.gradle' line: 149                                          

* What went wrong:
Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
>
  [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected

  Conflict between:
  - C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@portkey\react-native-sdk\node_modules\react-native-gesture-handler\package.json
  - C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\react-native-gesture-handler\package.json


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 47s
21 actionable tasks: 8 executed, 13 up-to-date
Error: C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
### My steps

1. npx create-expo-app -t expo-template-blank-typescript
2. npm install @portkey/react-native-sdk --save
3. npm i expo-dev-client
4. add resolution to package.json and install dependencies
5. npm run android

--> through the above error

### Some extra information maybe helpful
- os: window 11
- node version: v18.16.0
- java SDK: 17.0.9
- gradle: 8.0.1
- test project repo: [test-portkey-2](https://github.com/thiendangvan/test-portkey-2)

**Comment by carbon-portkey** [comment]
thank you for providing message to us, we will handle it soon 🤝

**Comment by FrankFeng1116** [comment]
thiendangvan, nice to solve the issue~
we can see the error message: 
> Task :react-native-gesture-handler:assertNoMultipleInstances FAILED
> [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected

>   Conflict between:
>  - C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\\@portkey\react-native-sdk\node_modules\react-native-gesture-handler\package.json
>  - C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\react-native-gesture-handler\package.json



This information represents you have  multiple versions of **react-native-gesture-handler**  npm package。  make sure add     `"react-native-gesture-handler": "2.9.0",` to the `resolutions`.  and then, do not forget execute `npm install`  again (important).   I think the `C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@portkey\react-native-sdk\node_modules\react-native-gesture-handler\` directory will disappear, and the conflict will be resolved.

**Comment by thiendangvan** [comment]
> thiendangvan, nice to solve the issue~ we can see the error message:
> 
> > Task :react-native-gesture-handler:assertNoMultipleInstances FAILED
> > [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected
> 
> > Conflict between:
> > 
> > * C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@portkey\react-native-sdk\node_modules\react-native-gesture-handler\package.json
> > * C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\react-native-gesture-handler\package.json
> 
> This information represents you have multiple versions of **react-native-gesture-handler** npm package。 make sure add `"react-native-gesture-handler": "2.9.0",` to the `resolutions`. and then, do not forget execute `npm install` again (important). I think the `C:\Users\thien.dangvan\ncc-workspace\test-portkey-2\node_modules\@portkey\react-native-sdk\node_modules\react-native-gesture-handler\` directory will disappear, and the conflict will be resolved.

hi [FrankFeng1116](https://github.com/FrankFeng1116), I already added the `"react-native-gesture-handler": "2.9.0",` to the `resolutions` but still got the same error. after I removed the  `"react-native-gesture-handler"` in the `dependencies` and ran `npm i` again that issue was gone.
![image](https://github.com/Portkey-Wallet/react-native-sdk/assets/154788705/33c9bbf7-6e09-4725-b2e6-3b13167d5d4f)

**Comment by thiendangvan** [comment]
after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks
![image](https://github.com/Portkey-Wallet/react-native-sdk/assets/154788705/27f0edd9-6398-4c9e-b19f-deffcac23c72)

**Comment by carbon-portkey** [comment]
> after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)

@thiendangvan  Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed.
Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.

**Comment by thiendangvan** [comment]
> > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> 
> @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.

I got it. Many thanks

**Comment by carbon-portkey** [comment]
> > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> 
> @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.

@thiendangvan we have created a PR: https://github.com/thiendangvan/test-portkey-2/pull/1 , and it worked well in our environment, please try it and see if there are more issues 😊 We will provide Guidance information on those issues later

**Comment by carbon-portkey** [comment]
> > > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> > 
> > 
> > @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.
> 
> @thiendangvan we have created a PR: [thiendangvan/test-portkey-2#1](https://github.com/thiendangvan/test-portkey-2/pull/1) , and it worked well in our environment, please try it and see if there are more issues 😊 We will provide Guidance information on those issues later

There‘s one more thing you need to follow: please use ```yarn``` instead of ```npm install``` to sync dependencies 🙏
And if you see issues about ```RNSVGRect```, you need to remove the ```android``` folder and rerun ```expo prebuild```, then regenerate the app in your device.

**Comment by thiendangvan** [comment]
> > > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> > 
> > 
> > @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.
> 
> @thiendangvan we have created a PR: [thiendangvan/test-portkey-2#1](https://github.com/thiendangvan/test-portkey-2/pull/1) , and it worked well in our environment, please try it and see if there are more issues 😊 We will provide Guidance information on those issues later

Thank you very much. let me take a look

**Comment by thiendangvan** [comment]
> > > > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> > > 
> > > 
> > > @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.
> > 
> > 
> > @thiendangvan we have created a PR: [thiendangvan/test-portkey-2#1](https://github.com/thiendangvan/test-portkey-2/pull/1) , and it worked well in our environment, please try it and see if there are more issues 😊 We will provide Guidance information on those issues later
> 
> There‘s one more thing you need to follow: please use `yarn` instead of `npm install` to sync dependencies 🙏 And if you see issues about `RNSVGRect`, you need to remove the `android` folder and rerun `expo prebuild`, then regenerate the app in your device.

okay noted. I will try to migrate from npm to yarn

**Comment by FrankFeng1116** [comment]
> > > > > after the build was successful, i tried to open it on my emulator device but got the below error. any ideas for that? thanks ![image](https://private-user-images.githubusercontent.com/154788705/293871244-27f0edd9-6398-4c9e-b19f-deffcac23c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzI5MDgsIm5iZiI6MTcwNDI3MjYwOCwicGF0aCI6Ii8xNTQ3ODg3MDUvMjkzODcxMjQ0LTI3ZjBlZGQ5LTYzOTgtNGM5ZS1iMTlmLWRlZmZjYWMyM2M3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFhMDMyOWZhYjk1NTNjN2Y5MzI5ZDY4MjllYjNhZWUyYmE3YzM1MmQ1MGIyN2NmMjZkNjRiZWFjYWU4NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.26JFBtgxu6gAIFB_-7vcg4_wUKB4gMmmq5-X80f2p6o)
> > > > 
> > > > 
> > > > @thiendangvan Sorry it's the same error we have faced during the video conferencing yesterday, all those errors come from the conflicting versions between our sdk project and the demo project =(, it makes two different versions of same dependencies are installed. Don't worry, we will fork your code repository and try to solve it. After that we will make a PR to you.
> > > 
> > > 
> > > @thiendangvan we have created a PR: [thiendangvan/test-portkey-2#1](https://github.com/thiendangvan/test-portkey-2/pull/1) , and it worked well in our environment, please try it and see if there are more issues 😊 We will provide Guidance information on those issues later
> > 
> > 
> > There‘s one more thing you need to follow: please use `yarn` instead of `npm install` to sync dependencies 🙏 And if you see issues about `RNSVGRect`, you need to remove the `android` folder and rerun `expo prebuild`, then regenerate the app in your device.
> 
> okay noted. I will try to migrate from npm to yarn

another [draft PR](https://github.com/thiendangvan/test-portkey-2/pull/2) can run by `npm`.    If you still want to use `npm` package manager

**Comment by carbon-portkey** [comment]
@thiendangvan Hi, is there more issues that we can deal with now? 😃

**Comment by thiendangvan** [comment]
> @thiendangvan Hi, is there more issues that we can deal with now? 😃

hi @carbon-portkey, I'm still checking and will get back to you tmr. thanks

**Comment by thiendangvan** [comment]
hi @carbon-portkey, I've tested both npm PR & npm PR and so far so good all SDK methods work. But there are some minor issues:
1. Making any change and saving the project will immediately crash the Android app
```
ERROR  Your app just crashed. See the error below.
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.devsupport.interfaces.DevLoadingViewManager.showMessage(java.lang.String)' on a null object reference
  com.facebook.react.modules.devloading.DevLoadingModule$1.run(DevLoadingModule.java:49)
  android.os.Handler.handleCallback(Handler.java:942)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:201)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7872)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  ```
  
  2. there are some warnings below and I'm not sure if they affect our app. If not maybe we can ignore them 😄
  
![image](https://github.com/Portkey-Wallet/react-native-sdk/assets/154788705/1151d101-417a-455f-9db8-094d4dc43b39)

**Comment by carbon-portkey** [comment]
> hi @carbon-portkey, I've tested both npm PR & npm PR and so far so good all SDK methods work. But there are some minor issues:
> 
> 1. Making any change and saving the project will immediately crash the Android app
> 
> ```
> ERROR  Your app just crashed. See the error below.
> java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.devsupport.interfaces.DevLoadingViewManager.showMessage(java.lang.String)' on a null object reference
>   com.facebook.react.modules.devloading.DevLoadingModule$1.run(DevLoadingModule.java:49)
>   android.os.Handler.handleCallback(Handler.java:942)
>   android.os.Handler.dispatchMessage(Handler.java:99)
>   android.os.Looper.loopOnce(Looper.java:201)
>   android.os.Looper.loop(Looper.java:288)
>   android.app.ActivityThread.main(ActivityThread.java:7872)
>   java.lang.reflect.Method.invoke(Native Method)
>   com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> ```
> 
> 2. there are some warnings below and I'm not sure if they affect our app. If not maybe we can ignore them 😄
> 
> ![image](https://private-user-images.githubusercontent.com/154788705/294800346-1151d101-417a-455f-9db8-094d4dc43b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODI5ODUsIm5iZiI6MTcwNDY4MjY4NSwicGF0aCI6Ii8xNTQ3ODg3MDUvMjk0ODAwMzQ2LTExNTFkMTAxLTQxN2EtNDU1Zi05ZGI4LTA5NGQ0ZGM0M2IzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMjU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjdjNTI3YzAwODI5NTIwZTdjMDg4Y2M0OGMzN2M0ZjUzN2QyZDk4M2JiMjEzYTdiN2MxNmNiZTU5MTc0YmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IKXf-3dyCI6hrp0b06V9_sRaVo9wne8evLoWEboKcd0)

@thiendangvan Glad to hear that you have successfully installed the SDK =) 
For question 1, it seems that some codes from react-native were not linked correctly, please use ```yarn``` or ```npm install```, then use ```npm run android``` to regenerate the Android APP on your device, if this doesn't work, then try to remove the ```/android``` folder and try the ```npx expo prebuild``` command again 🙏
For question 2, it comes from some system modules that do not have the declared ```addListener``` method, and this will not cause troubles, you can ignore them 😃

**Comment by thiendangvan** [comment]
hi @carbon-portkey, it seems we can not login to another account, it always asks to enter a passcode when i try to logout and login again. can you check it? thanks
https://drive.google.com/file/d/1qP88Hp3OGkRMXgfDQgz1rwdKT-y7rgD7/view?usp=sharing

**Comment by thiendangvan** [comment]
btw i wanna ask which method i can use to get the balance of current account? I've tried the `getWalletInfo` but it does not return the balance

**Comment by wade-portkey** [comment]
> hi @carbon-portkey, it seems we can not login to another account, it always asks to enter a passcode when i try to logout and login again. can you check it? thanks https://drive.google.com/file/d/1qP88Hp3OGkRMXgfDQgz1rwdKT-y7rgD7/view?usp=sharing

hi, @thiendangvan . If you want to log out, you should click the "EXITWALLET"
button, which is at the bottom of the page. The click event of this button is a Promise function, so you should use `await` to get the result.

**Comment by wade-portkey** [comment]
> btw i wanna ask which method i can use to get the balance of current account? I've tried the `getWalletInfo` but it does not return the balance

The ability to get a balance is not currently supported, and it will be supported in the next release version. 
If you just want to see the balance, you can use the `openAssetsDashboard` function.

**Comment by carbon-portkey** [comment]
> > btw i wanna ask which method i can use to get the balance of current account? I've tried the `getWalletInfo` but it does not return the balance
> 
> The ability to get a balance is not currently supported, and it will be supported in the next release version. If you just want to see the balance, you can use the `openAssetsDashboard` function.

@thiendangvan We are about to publish the next version of our SDK this Friday, and this API will be added =)

**Comment by thiendangvan** [comment]
hi @carbon-portkey, it seems we cannot 

> > hi @carbon-portkey, it seems we can not login to another account, it always asks to enter a passcode when i try to logout and login again. can you check it? thanks https://drive.google.com/file/d/1qP88Hp3OGkRMXgfDQgz1rwdKT-y7rgD7/view?usp=sharing
> 
> hi, @thiendangvan . If you want to log out, you should click the "EXITWALLET" button, which is at the bottom of the page. The click event of this button is a Promise function, so you should use `await` to get the result.

it's ok now, thanks @wade-portkey

**Comment by thiendangvan** [comment]
> > > btw i wanna ask which method i can use to get the balance of current account? I've tried the `getWalletInfo` but it does not return the balance
> > 
> > 
> > The ability to get a balance is not currently supported, and it will be supported in the next release version. If you just want to see the balance, you can use the `openAssetsDashboard` function.
> 
> @thiendangvan We are about to publish the next version of our SDK this Friday, and this API will be added =)

nice, that's great to hear 😄
