### ISSUE TITLE
Android - Lost cookie after connect to wallet

### ISSUE THREAD

**Issue by thiendangvan** [Portkey-Wallet/react-native-sdk#78]
**Describe the bug**

Lost cookie after connecting to a wallet. I've created a sample project so you can reproduce for the issue
<br>
**Necessary information**
https://github.com/thiendangvan/test-portkey-2

**To Reproduce**

1. Login to app
2. Login to wallet
3. observer: the user will be redirected to the login page (caused by loss of cookies)
 <br>

**Expected behavior**

the cookie should not be cleared after connecting to a wallet
 <br>

**Screenshots**

https://drive.google.com/file/d/1XQf-Z_TixcI-vd-AICZBDHtxAo3-X7Ls/view?usp=sharing
<br>

**Environment (please complete the following information):**
 - OS: Android
 - Version 13
 <br>

**Additional context** <br>

it seems the captcha is the cause of the lost cookie issue
it does not happen on IOS

**Comment by FrankFeng1116** [comment]
> **Describe the bug**
> 
> Lost cookie after connecting to a wallet. I've created a sample project so you can reproduce for the issue **Necessary information** https://github.com/thiendangvan/test-portkey-2
> 
> **To Reproduce**
> 
> 1. Login to app
> 2. Login to wallet
> 3. observer: the user will be redirected to the login page (caused by loss of cookies)
> 
> 
> **Expected behavior**
> 
> the cookie should not be cleared after connecting to a wallet
> 
> **Screenshots**
> 
> https://drive.google.com/file/d/1XQf-Z_TixcI-vd-AICZBDHtxAo3-X7Ls/view?usp=sharing
> 
> **Environment (please complete the following information):**
> 
> * OS: Android
> * Version 13
> 
> 
> **Additional context**
> 
> it seems the captcha is the cause of the lost cookie issue it does not happen on IOS

hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project.   but  I have watched the video you shared.  Have you tried not calling Portkey SDK， just call the `/api/get-something` by `setTimeout`？<br/>
`portkey` uses a custom network framework， which will not affect `axios`.  In addition, I learned through google search that axios does not come with cookies by default, which may be related to the use of axios. so I think the loss of the cookie may be not caused by the portkey SDK.  

You need to confirm if the server settings are correct, and you need to ensure that the cookie has not expired.  and You can refer to the following link: 
https://stackoverflow.com/questions/46502537/react-native-axios-not-persisting-cookies-across-requests
https://blog.csdn.net/qq_38157825/article/details/115109840

**Comment by thiendangvan** [comment]
> hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared. 
> 

hi @FrankFeng1116, 
could you try to run the mock server and change the baseUrl to your device IP?

>Have you tried not calling Portkey SDK， just call the `/api/get-something` by `setTimeout`？ 
>
let me try

>portkey uses a custom network framework， which will not affect axios. In addition, I learned through google search that axios does not come with cookies by default, which may be related to the use of axios. so I think the loss of the cookie may be not caused by the portkey SDK.

>You need to confirm if the server settings are correct, and you need to ensure that the cookie has not expired. and You can refer to the following link:
https://stackoverflow.com/questions/46502537/react-native-axios-not-persisting-cookies-across-requests
https://blog.csdn.net/qq_38157825/article/details/115109840
>
i see, let me check

**Comment by FrankFeng1116** [comment]
> > hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared.
> 
> hi @FrankFeng1116, could you try to run the mock server and change the baseUrl to your device IP?

Sorry,  I didn't notice the mock-server-2 project.  I will check again.

**Comment by thiendangvan** [comment]
> > > hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared.
> > 
> > 
> > hi @FrankFeng1116, could you try to run the mock server and change the baseUrl to your device IP?
> 
> Sorry, I didn't notice the mock-server-2 project. I will check again.

Have you found out what's causing the problem? i think it may related to the cookie management mechanism on Android
some other issues related to the cookies: 
https://reactnative.dev/docs/network#known-issues-with-fetch-and-cookie-based-authentication

**Comment by FrankFeng1116** [comment]
> > > > hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared.
> > > 
> > > 
> > > hi @FrankFeng1116, could you try to run the mock server and change the baseUrl to your device IP?
> > 
> > 
> > Sorry, I didn't notice the mock-server-2 project. I will check again.
> 
> Have you found out what's causing the problem? i think it may related to the cookie management mechanism on Android some other issues related to the cookies: https://reactnative.dev/docs/network#known-issues-with-fetch-and-cookie-based-authentication

the same doubts.   but I haven't found the real place to manage cookies yet. We will continue to follow up on this issue.
and I will check the link you sent

**Comment by thiendangvan** [comment]
> > > > > hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared.
> > > > 
> > > > 
> > > > hi @FrankFeng1116, could you try to run the mock server and change the baseUrl to your device IP?
> > > 
> > > 
> > > Sorry, I didn't notice the mock-server-2 project. I will check again.
> > 
> > 
> > Have you found out what's causing the problem? i think it may related to the cookie management mechanism on Android some other issues related to the cookies: https://reactnative.dev/docs/network#known-issues-with-fetch-and-cookie-based-authentication
> 
> the same doubts. but I haven't found the real place to manage cookies yet. We will continue to follow up on this issue. and I will check the link you sent

many thanks 🙏

**Comment by FrankFeng1116** [comment]
> > > > > > hi！ @thiendangvan ， Your demo project is using the Internal IP， so I am unable to run your demo project. but I have watched the video you shared.
> > > > > 
> > > > > 
> > > > > hi @FrankFeng1116, could you try to run the mock server and change the baseUrl to your device IP?
> > > > 
> > > > 
> > > > Sorry, I didn't notice the mock-server-2 project. I will check again.
> > > 
> > > 
> > > Have you found out what's causing the problem? i think it may related to the cookie management mechanism on Android some other issues related to the cookies: https://reactnative.dev/docs/network#known-issues-with-fetch-and-cookie-based-authentication
> > 
> > 
> > the same doubts. but I haven't found the real place to manage cookies yet. We will continue to follow up on this issue. and I will check the link you sent
> 
> many thanks 🙏

Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.

**Comment by thiendangvan** [comment]
> Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.

great great, pls let me know when the new version is ready 🤝

**Comment by FrankFeng1116** [comment]
> > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> 
> great great, pls let me know when the new version is ready 🤝

@thiendangvan,  Hi!
we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`

**Comment by thiendangvan** [comment]
> > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > 
> > 
> > great great, pls let me know when the new version is ready 🤝
> > @thiendangvan,  Hi!
> > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`

thanks thanks, i will try and feedback to you later

**Comment by FrankFeng1116** [comment]
> > > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > > 
> > > 
> > > great great, pls let me know when the new version is ready 🤝
> > > @thiendangvan,  Hi!
> > > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`
> 
> thanks thanks, i will try and feedback to you later

Hi! @thiendangvan 
Is there any further feedback?

**Comment by thiendangvan** [comment]
> > > > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > > > 
> > > > 
> > > > great great, pls let me know when the new version is ready 🤝
> > > > @thiendangvan,  Hi!
> > > > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`
> > 
> > 
> > thanks thanks, i will try and feedback to you later
> 
> Hi! @thiendangvan Is there any further feedback?

Hi @FrankFeng1116, login flow works fine right now, good job 👍👍
but i'd like to know how your team solved this issue.🤔

**Comment by FrankFeng1116** [comment]
> > > > > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > > > > 
> > > > > 
> > > > > great great, pls let me know when the new version is ready 🤝
> > > > > @thiendangvan,  Hi!
> > > > > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`
> > > 
> > > 
> > > thanks thanks, i will try and feedback to you later
> > 
> > 
> > Hi! @thiendangvan Is there any further feedback?
> 
> Hi @FrankFeng1116, login flow works fine right now, good job 👍👍 but i'd like to know how your team solved this issue.🤔

Our portkey sdk uses the `WebView` component of `react-native-webview`,   The `WebView` component clearing cache operation will affect the cookies of axios network requests (This is a mechanism for React Native on Android).   We‘ve modified the caching strategy of WebView.  
This is a screenshot of the key code
![img_v3_027l_f7850be7-1401-4653-8336-3fa21079d77g](https://github.com/Portkey-Wallet/react-native-sdk/assets/149366454/a1c2c829-9ca8-4b6d-8177-57e1664e0240)

**Comment by thiendangvan** [comment]
> > > > > > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > > > > > 
> > > > > > 
> > > > > > great great, pls let me know when the new version is ready 🤝
> > > > > > @thiendangvan,  Hi!
> > > > > > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`
> > > > 
> > > > 
> > > > thanks thanks, i will try and feedback to you later
> > > 
> > > 
> > > Hi! @thiendangvan Is there any further feedback?
> > 
> > 
> > Hi @FrankFeng1116, login flow works fine right now, good job 👍👍 but i'd like to know how your team solved this issue.🤔
> 
> Our portkey sdk uses the `WebView` component of `react-native-webview`, The `WebView` component clearing cache operation will affect the cookies of axios network requests (This is a mechanism for React Native on Android). We‘ve modified the caching strategy of WebView. This is a screenshot of the key code ![img_v3_027l_f7850be7-1401-4653-8336-3fa21079d77g](https://private-user-images.githubusercontent.com/149366454/301769753-a1c2c829-9ca8-4b6d-8177-57e1664e0240.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjA4MjUsIm5iZiI6MTcwNjg2MDUyNSwicGF0aCI6Ii8xNDkzNjY0NTQvMzAxNzY5NzUzLWExYzJjODI5LTljYTgtNGI2ZC04MTc3LTU3ZTE2NjRlMDI0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNzU1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDA5YjI4YmEyYTU4ZmVkZGJiMWNhZTU0MTUzYjA2MDMwYjcxODVmMTU4MzY5ZmYwMWZlYzQwYTJjMGQ1YThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSfvz-B_0pMMHwkWGs5zj2SoC31tW7nuWJf1v4E3t0c)

okay i see

**Comment by FrankFeng1116** [comment]
> > > > > > > > Hi, @thiendangvan Your idea is absolutely right, it is indeed related to the cookie management mechanism on the Android platform. We‘ve found a solution and will release a new version later to address this issue.
> > > > > > > 
> > > > > > > 
> > > > > > > great great, pls let me know when the new version is ready 🤝
> > > > > > > @thiendangvan,  Hi!
> > > > > > > we've already released a new version of `@pokey/react-native-sdk`,    the version is `1.0.0-alpha.6`
> > > > > 
> > > > > 
> > > > > thanks thanks, i will try and feedback to you later
> > > > 
> > > > 
> > > > Hi! @thiendangvan Is there any further feedback?
> > > 
> > > 
> > > Hi @FrankFeng1116, login flow works fine right now, good job 👍👍 but i'd like to know how your team solved this issue.🤔
> > 
> > 
> > Our portkey sdk uses the `WebView` component of `react-native-webview`, The `WebView` component clearing cache operation will affect the cookies of axios network requests (This is a mechanism for React Native on Android). We‘ve modified the caching strategy of WebView. This is a screenshot of the key code ![img_v3_027l_f7850be7-1401-4653-8336-3fa21079d77g](https://private-user-images.githubusercontent.com/149366454/301769753-a1c2c829-9ca8-4b6d-8177-57e1664e0240.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjA4MjUsIm5iZiI6MTcwNjg2MDUyNSwicGF0aCI6Ii8xNDkzNjY0NTQvMzAxNzY5NzUzLWExYzJjODI5LTljYTgtNGI2ZC04MTc3LTU3ZTE2NjRlMDI0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNzU1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDA5YjI4YmEyYTU4ZmVkZGJiMWNhZTU0MTUzYjA2MDMwYjcxODVmMTU4MzY5ZmYwMWZlYzQwYTJjMGQ1YThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSfvz-B_0pMMHwkWGs5zj2SoC31tW7nuWJf1v4E3t0c)
> 
> okay i see

I will close this issue.  Feel free to submit issues if you have any questions
